version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bankdb
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bank-net

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: bank-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - bank-net

volumes:
  db-data:

networks:
  bank-net:
