spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # для теста, чтобы таблицы создавались автоматически
    show-sql: true
  security:
    user:
      name: admin
      password: admin123
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  liquibase:
#    change-log: classpath:db/migration/changelog-master.xml
